Refactorisation + Intégration travail des perfs
PnX-SI/gn_module_export pull request #155
Opened 2023-05-11 19:04 UTC by amandine-sahl

2023-05-11 20:36 UTC, mvergez requested changes
Parfait ! Merci pour cette PR et pour l'intégration en avance de la PR des perfs !

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/commands.py
> +            scheduled_export=export_schedule,
scheduled_export vs export_schedule

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/commands.py
> +    except NotFound:
Catch `Forbidden` ?

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/utils_export.py
> +            self.test_schedule_needded()
needed

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/utils_export.py
> +            return self.export_dir + "/" + self.file_name
Serait-il possible d'utiliser `pathlib` ?

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/utils_export.py
>              self.export_dir = os.path.join(
Serait-il possible d'utiliser `pathlib` ?

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/utils_export.py
> +        return self.export_dir + "/" + self.file_name
Serait-il possible d'utiliser `pathlib` ?

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/blueprint.py
> +        + "/"
Supprimer le paramètre `usr_generated_dirname`. Car les utilisateurs pourraient renseigner un chemin absolu ce qui ferait planter url_for.
De plus, cela devient obsolète car apache sert maintenant le dossier `media`
Peut être à remplacer par une constante

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/tasks.py
>      for scheduled_export in ExportSchedules.query.all():
```python
try:
   export_request = ExportRequest(
            id_export=scheduled_export.id_export, scheduled_export=scheduled_export
        )
except ExportNotNeeded:
   continue
```

2023-05-11 20:36 UTC, mvergez commented on backend/gn_module_export/tasks.py
>  @celery_app.task(bind=True, throws=ExportGenerationNotNeeded)
Supprimer : `ExportNotNeeded`

2023-05-12 09:42 UTC, bouttier commented on backend/gn_module_export/tasks.py
> +            export_url=None,
Voir si on ne peut pas mettre la génération de export_url dans ExportRequest

2023-05-12 09:42 UTC, bouttier commented on backend/gn_module_export/utils_export.py
> +    def __init__(self, id_export, scheduled_export=None, user=None, format=None):
```suggestion
    def __init__(self, id_export, user=None, format=None):
```

2023-05-12 09:42 UTC, bouttier commented on backend/gn_module_export/utils_export.py
> +            return Path(self.export_dir) / self.file_name
à l’init

2023-05-12 09:42 UTC, bouttier commented on backend/gn_module_export/utils_export.py
> +    notify_export_file_generated(export=export, user=id_role, export_url=export_url)
```suggestion
    else:
        notify_export_file_generated(export=export, user=id_role, export_url=export_url)
```

2023-05-12 09:46 UTC, merged